# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=7, null=True)),
                ('cell_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('total_value', models.IntegerField()),
                ('total_iva', models.IntegerField()),
                ('total_rte', models.IntegerField()),
                ('client_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Document_type')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices_has_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('packing', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('iva', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoices_has_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product'),
        ),
        migrations.AddField(
            model_name='client',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Document_type'),
        ),
    ]
