# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document_type',
            new_name='DocumentType',
        ),
    ]
