# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20170722_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_document_type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
